#
# cogs/misc/inspirobot.py
#
# futaba - A Discord Mod bot for the Programming server
# Copyright (c) 2017-2020 Jake Richardson, Ammon Smith, jackylam5
#
# futaba is available free of charge under the terms of the MIT
# License. You are free to redistribute and/or modify it under those
# terms. It is distributed in the hopes that it will be useful, but
# WITHOUT ANY WARRANTY. See the LICENSE file for more details.
#

""" Cog for InspiroBot image generation. """

import logging

import aiohttp
import discord
from discord.ext import commands

from ..abc import AbstractCog

logger = logging.getLogger(__name__)

__all__ = ["InspiroBot"]

INSPIROBOT_API = "https://inspirobot.me/api?generate=true"


class InspiroBot(AbstractCog):
    __slots__ = ("journal",)

    def __init__(self, bot):
        super().__init__(bot)
        self.journal = bot.get_broadcaster("/inspirobot")

    def setup(self):
        pass

    @commands.command(name="inspirobot", aliases=["inspire", "inspireme"])
    async def inspirobot(self, ctx):
        """ Returns an image generated by InspiroBot. """
        async with aiohttp.ClientSession(raise_for_status=True) as session:
            async with session.get(INSPIROBOT_API) as api_resp:
                image_url = await api_resp.text()

                content = f"Got generated image {image_url} from InspiroBot"
                self.journal.send("api/success", ctx.guild, content, icon="ok")

                embed = discord.Embed()
                embed.title = "Be inspired."
                embed.set_image(url=image_url)
                await ctx.send(embed=embed)
