#
# cogs/optional/simplewriter/words/core_words_list.py
#
# futaba - A Discord Mod bot for the Programming server
# Copyright (c) 2017-2020 Jake Richardson, Ammon Smith, jackylam5, Joshua 'joshuas3' Stockin
#
# futaba is available free of charge under the terms of the MIT
# License. You are free to redistribute and/or modify it under those
# terms. It is distributed in the hopes that it will be useful, but
# WITHOUT ANY WARRANTY. See the LICENSE file for more details.
#

__all__ = ["core_words_list"]

# The list of the most frequently used English words, plus their directly related derivatives.
core_words_list = [
	"a", "an",
	"able",
	"about",
	"accept", "accepts", "accepted", "accepting",
	"across",
	"act", "acts", "acted", "acting",
	"add", "adds", "added", "adding",
	"admit", "admits", "admitted", "admitting",
	"after",
	"afternoon", "afternoons",
	"again",
	"against",
	"age", "ages", "aged", "aging",
	"ago",
	"agree", "agrees", "agreed", "agreeing",
	"air", "airs", "aired", "airing",
	"all",
	"allow", "allows", "allowed", "allowing", "allower", "allowers",
	"almost",
	"along",
	"already",
	"also",
	"always",
	"and",
	"another",
	"answer", "answers", "answered", "answering",
	"any",
	"anything",
	"appear", "appears", "appeared", "appearing",
	"approach", "approaches", "approached", "approaching",
	"area", "areas",
	"arm", "arms", "armed", "arming",
	"around",
	"art", "arts",
	"as",
	"ask", "asks", "asked", "asking",
	"at",
	"away",
	"baby", "babies",
	"back", "backs", "backed", "backing",
	"bad", "worse", "worst",
	"bag", "bags", "bagged", "bagging",
	"ball", "balls", "balled", "balling",
	"bank", "banks", "banked", "banking",
	"bar", "bars",
	"be",
	"bear", "bears", "bore", "born", "bearing",
	"beat", "beats", "beat", "beaten", "beating",
	"because",
	"become", "becomes", "became", "become", "becoming",
	"bed", "beds", "bedded", "bedding",
	"before",
	"begin", "begins", "began", "begun", "beginning",
	"behind",
	"being",
	"believe", "believes", "believed", "believing", "believer", "believers",
	"best", "better", "best", "bests", "bested", "besting",
	"between",
	"big", "bigger", "biggest",
	"bit", "bits", "bites", "bit", "biting", "biter", "biters",
	"black", "blacks", "blacker", "blackest", "blacking",
	"blood", "bloods",
	"blow", "blows", "blew", "blown", "blowing", "blower", "blowers",
	"blue", "blues", "bluer", "bluest",
	"board", "boards", "boarded", "boarding",
	"boat", "boats", "boated", "boating",
	"body", "bodies",
	"book", "books", "booked", "booking",
	"both",
	"bother", "bothers", "bothered", "bothering",
	"bottle", "bottles", "bottled", "bottling",
	"bottom", "bottoms", "bottomed", "bottoming",
	"box", "boxes", "boxed", "boxing",
	"boy", "boys",
	"break", "breaks", "broke", "broken", "breaking", "breaker", "breakers",
	"bring", "brings", "brought", "bringing",
	"brother", "brothers",
	"build", "builds", "built", "building", "builder", "builders",
	"bus", "buses", "bused", "busing",
	"business", "businesses",
	"busy", "busier", "busiest", "busied", "busying",
	"but",
	"buy", "buys", "bought", "buying",
	"by",
	"call", "calls", "called", "calling",
	"can", "cans",
	"car", "cars",
	"card", "cards", "carded", "carding",
	"care", "cares", "cared", "caring",
	"carry", "carries", "carried", "carrying", "carrier", "carriers",
	"case", "cases", "cased", "casing",
	"cat", "cats", "catted", "catting",
	"catch", "catches", "caught", "catching", "catcher",
	"cause", "causes", "caused", "causing",
	"center", "centers", "centered", "centering",
	"certain",
	"chair", "chairs",
	"chance", "chances", "chanced", "chancing",
	"change", "changes", "changed", "changing", "changer",
	"check", "checks", "checked", "checking", "checker", "checkers",
	"child", "children",
	"choice", "choices", "choicer", "choicest",
	"choose", "chooses", "chose", "chosen", "choosing", "chooser", "choosers",
	"church", "churches",
	"city", "cities",
	"class", "classes",
	"clean", "cleaner", "cleanest", "cleans", "cleaned", "cleaning", "cleaners",
	"clear", "clearer", "clearest", "clears", "cleared", "clearing",
	"close", "closes", "closed", "closing", "closer", "closest",
	"clothe", "clothes", "clothed", "clothing",
	"coffee", "coffees",
	"cold", "colder", "coldest", "colds",
	"college", "colleges",
	"color", "colors", "colored", "coloring",
	"come", "comes", "came", "come", "coming",
	"company", "companies",
	"consider", "considers", "considered", "considering",
	"continue", "continues", "continued", "continuing",
	"control", "controls", "controlled", "controlling",
	"corner", "corners", "cornered", "cornering",
	"could",
	"count", "counts", "counted", "counting", "counter", "counters",
	"country", "countries",
	"couple", "couples",
	"course", "courses", "coursed", "coursing",
	"cover", "covers", "covered", "covering",
	"create", "creates", "created", "creating",
	"cross", "crosses", "crossed", "crossing", "crosser",
	"cup", "cups", "cupped", "cupping",
	"cut", "cuts", "cut", "cutting",
	"dad", "dads",
	"day", "days",
	"dead", "deader", "deadest",
	"decide", "decides", "decided", "deciding",
	"deep", "deeper", "deepest",
	"die", "dies", "died", "dying",
	"dinner", "dinners",
	"do", "does", "did", "done", "doing",
	"doctor", "doctors", "doctored", "doctoring",
	"dog", "dogs", "dogged", "dogging",
	"door", "doors",
	"down", "downs",
	"draw", "draws", "drew", "drawn", "drawing",
	"dress", "dresses", "dressed", "dressing",
	"drink", "drinks", "drank", "drunk", "drinking", "drinker", "drinkers",
	"drive", "drives", "drove", "driven", "driving", "driver", "drivers",
	"drop", "drops", "dropped", "dropping",
	"dry", "drier", "driest", "dries", "dried", "drying",
	"during",
	"each",
	"early", "earlier", "earliest",
	"east",
	"easy", "easier", "easiest",
	"eat", "eats", "ate", "eaten", "eating",
	"egg", "eggs", "egged", "egging",
	"eight", "eights",
	"either",
	"else",
	"end", "ends", "ended", "ending",
	"engine", "engines",
	"enjoy", "enjoys", "enjoyed", "enjoying",
	"enough",
	"enter", "enters", "entered", "entering",
	"especially",
	"even", "evens", "evened",
	"ever",
	"every",
	"except", "excepts", "excepted", "excepting",
	"expect", "expects", "expected", "expecting",
	"explain", "explains", "explained", "explaining", "explainer", "explainers",
	"extra", "extras",
	"eye", "eyes", "eyed", "eying",
	"face", "faces", "faced", "facing",
	"fact", "facts",
	"fall", "falls", "fell", "fallen", "falling",
	"family", "families",
	"far", "farther", "farthest", "further", "furthest",
	"fast", "faster", "fastest",
	"father", "fathers", "fathered", "fathering",
	"feed", "feeds", "fed", "feeding",
	"feel", "feels", "felt", "feeling",
	"few", "fewer", "fewest",
	"field", "fields",
	"fight", "fights", "fought", "fighting", "fighter", "fighters",
	"figure", "figures", "figured", "figuring",
	"fill", "fills", "filled", "filling",
	"final", "finals",
	"find", "finds", "found", "finding", "finder", "finders",
	"fine", "finer", "finest", "fines", "fined", "fining",
	"finish", "finishes", "finished", "finishing",
	"fire", "fires", "fired", "firing",
	"first", "firsts",
	"fish", "fishes", "fished", "fishing",
	"fit", "fits", "fitted", "fitting", "fitter", "fittest",
	"five", "fives",
	"flat", "flatter", "flattest", "flats", "flatted", "flatting",
	"floor", "floors",
	"fly", "flies", "flew", "flown", "flying",
	"follow", "follows", "followed", "following",
	"food", "foods",
	"foot", "feet", "foots", "footed", "footing",
	"for",
	"force", "forces", "forced", "forcing",
	"forget", "forgets", "forgot", "forgotten", "forgetting", "forgetter", "forgetters",
	"form", "forms", "formed", "forming",
	"forward", "forwards", "forwarded", "forwarding",
	"four", "fours",
	"free", "freer", "freest", "frees", "freed", "freeing",
	"friend", "friends",
	"from",
	"front", "fronts", "fronted", "fronting",
	"full", "fuller", "fullest",
	"fun",
	"further", "farther", "farthest", "further", "furthest",
	"future", "futures",
	"game", "games", "gamed", "gaming", "gamer", "gamers",
	"garden", "gardens", "gardened", "gardening",
	"get", "gets", "got", "getting", "gotten",
	"girl", "girls",
	"give", "gives", "gave", "given", "giving",
	"glass", "glasses",
	"go", "goes", "went", "gone", "going",
	"god", "gods",
	"good", "better", "best", "goods",
	"great", "greater", "greatest",
	"green", "greens", "greener", "greenest",
	"ground", "grounds", "ground",
	"group", "groups", "grouped", "grouping",
	"grow", "grows", "grew", "grown", "growing",
	"guess", "guesses", "guessed", "guessing",
	"guy", "guys",
	"hair", "hairs",
	"half", "halves",
	"hall", "halls",
	"hand", "hands", "handed", "handing",
	"hang", "hangs", "hung", "hanging", "hanged",
	"happen", "happens", "happened", "happening",
	"happy", "happier", "happiest",
	"hard", "harder", "hardest",
	"hate", "hates", "hated", "hating",
	"have", "has", "had", "having",
	"he",
	"head", "heads", "headed", "heading",
	"hear", "hears", "heard", "hearing",
	"heart", "hearts",
	"heat", "heats", "heated", "heating", "heater", "heaters",
	"heavy", "heavier", "heaviest",
	"hell", "hells",
	"hello", "hellos",
	"help", "helps", "helped", "helping",
	"here", "heres",
	"hey",
	"hi",
	"high", "higher", "highest",
	"history", "histories",
	"hit", "hits", "hit", "hitting", "hitter", "hitters",
	"hold", "holds", "held", "holding", "holder", "holders",
	"home", "homes",
	"hope", "hopes", "hoped", "hoping",
	"horse", "horses",
	"hospital", "hospitals",
	"hot", "hotter", "hottest",
	"hour", "hours",
	"house", "houses", "housed", "housing",
	"how",
	"however",
	"hundred", "hundreds",
	"husband", "husbands",
	"idea", "ideas",
	"if",
	"imagine", "imagines", "imagined", "imagining", "imaginer", "imaginers",
	"important",
	"in",
	"inside", "insides",
	"instead",
	"interest", "interests", "interested", "interesting",
	"into",
	"it",
	"job", "jobs",
	"join", "joins", "joined", "joining",
	"jump", "jumps", "jumped", "jumping", "jumper", "jumpers",
	"just",
	"keep", "keeps", "kept", "keeping", "keeper", "keepers",
	"key", "keys", "keyed", "keying",
	"kid", "kids", "kidded", "kidding",
	"kill", "kills", "killed", "killing", "killer", "killers",
	"kind", "kinds", "kinder", "kindest",
	"kitchen", "kitchens",
	"knock", "knocks", "knocked", "knocking",
	"know", "knows", "knew", "known", "knowing",
	"lady", "ladies",
	"land", "lands", "landed", "landing", "lander", "landers",
	"language", "languages",
	"large", "larger", "largest",
	"last", "lasts", "lasted", "lasting",
	"late", "later",
	"laugh", "laughs", "laughed", "laughing",
	"law", "laws",
	"lay", "lays", "laid", "laying",
	"layer", "layers",
	"lead", "leads", "led", "leading", "leader", "leaders",
	"learn", "learns", "learned", "learning",
	"leave", "leaves", "left", "leaving",
	"left", "leaves", "left", "leaving",
	"leg", "legs",
	"less", "lesser", "least",
	"let", "lets", "let", "letting",
	"letter", "letters",
	"lie", "lies", "lay", "lying", "lied",
	"life", "lives",
	"light", "lights", "lighter", "lightest", "lighted", "lighting", "lit", "lighters",
	"like", "likes", "liked", "liking",
	"line", "lines", "lined", "lining",
	"listen", "listens", "listened", "listening",
	"little", "littler", "littlest", "less", "least",
	"live", "lives", "lived", "living",
	"local", "locals",
	"lock", "locks", "locked", "locking",
	"long", "longer", "longest", "longs", "longed", "longing",
	"look", "looks", "looked", "looking", "looker", "lookers",
	"lose", "loses", "lost", "losing",
	"lot", "lots",
	"love", "loves", "loved", "loving", "lover", "lovers",
	"low", "lower", "lowest",
	"lunch", "lunches", "lunched", "lunching",
	"machine", "machines", "machined", "machining",
	"main", "mains",
	"make", "makes", "made", "making", "maker", "makers",
	"man", "men",
	"manage", "manages", "managed", "managing",
	"many", "more", "most",
	"mark", "marks", "marked", "marking",
	"marry", "marries", "married", "marrying",
	"matter", "matters", "mattered", "mattering",
	"may", "mays",
	"maybe",
	"mean", "means", "meant", "meaning", "meanest",
	"meaning", "meanings", "means", "meant", "meaning",
	"meet", "meets", "met", "meeting",
	"member", "members",
	"mention", "mentions", "mentioned", "mentioning",
	"middle", "middles",
	"might", "mights",
	"mind", "minds", "minded", "minding",
	"minute", "minutes",
	"miss", "misses", "missed", "missing",
	"moment", "moments",
	"money", "monies",
	"month", "months",
	"more", "more", "most",
	"morning", "mornings",
	"most", "more", "most",
	"mother", "mothers", "mothered", "mothering",
	"move", "moves", "moved", "moving",
	"much",
	"music", "musics",
	"must",
	"name", "names", "named", "naming",
	"near", "nearer", "nearest", "nears", "neared", "nearing",
	"need", "needs", "needed", "needing",
	"never",
	"new", "newer", "newest",
	"news",
	"next",
	"nice", "nicer", "nicest",
	"night", "nights",
	"no",
	"none",
	"normal",
	"north",
	"not",
	"note", "notes", "noted", "noting",
	"notice", "notices", "noticed", "noticing",
	"now",
	"number", "numbers", "numbered", "numbering", "number",
	"of",
	"off", "offs", "offed", "offing",
	"offer", "offers", "offered", "offering",
	"office", "offices",
	"often",
	"okay", "okays", "okayed", "okaying",
	"old", "older", "oldest",
	"on",
	"once",
	"one", "ones",
	"only",
	"open", "opens", "opened", "opening",
	"or",
	"order", "orders", "ordered", "ordering",
	"other", "others",
	"out", "outs",
	"over", "overs",
	"own", "owns", "owned", "owning", "owner", "owners",
	"page", "pages", "paged", "paging",
	"paint", "paints", "painted", "painting",
	"pair", "pairs", "paired", "pairing",
	"paper", "papers",
	"parent", "parents", "parented", "parenting",
	"part", "parts", "parted", "parting",
	"party", "parties", "partied", "partying",
	"pass", "passes", "passed", "passing",
	"past", "pasts",
	"pay", "pays", "paid", "paying",
	"people", "persons", "peoples", "peopled", "peopling",
	"perfect", "perfects", "perfected", "perfecting",
	"perhaps",
	"person", "persons",
	"pick", "picks", "picked", "picking",
	"picture", "pictures", "pictured", "picturing",
	"piece", "pieces", "pieced", "piecing",
	"place", "places", "placed", "placing",
	"plan", "plans", "planned", "planning",
	"play", "plays", "played", "playing", "player", "players",
	"please", "pleases", "pleased", "pleasing",
	"point", "points", "pointed", "pointing", "pointer", "pointers",
	"police", "polices", "policed", "policing",
	"poor", "poorer", "poorest",
	"position", "positions", "positioned", "positioning",
	"possible",
	"power", "powers", "powered", "powering",
	"prepare", "prepares", "prepared", "preparing",
	"press", "presses", "pressed", "pressing",
	"pretty", "prettier", "prettiest",
	"probably",
	"problem", "problems",
	"pull", "pulls", "pulled", "pulling", "puller", "pullers",
	"push", "pushes", "pushed", "pushing", "pusher", "pushers",
	"put", "puts", "put", "putting",
	"question", "questions", "questioned", "questioning", "questioner", "questioners",
	"quick", "quicker", "quickest",
	"quiet", "quieter", "quietest", "quiets", "quieted", "quieting",
	"quite",
	"radio", "radios",
	"raise", "raises", "raised", "raising",
	"rather",
	"read", "reads", "reading",
	"ready", "readier", "readiest", "readies", "readied", "readying",
	"real", "realer", "realest",
	"realize", "realizes", "realized", "realizing",
	"really",
	"reason", "reasons", "reasoned", "reasoning",
	"receive", "receives", "received", "receiving",
	"recognize", "recognizes", "recognized", "recognizing",
	"red", "reds", "redder", "reddest",
	"remember", "remembers", "remembered", "remembering",
	"rest", "rests", "rested", "resting",
	"return", "returns", "returned", "returning",
	"rid",
	"right", "righter", "rights", "righted", "righting",
	"ring", "rings", "rang", "rung", "ringing", "ringed",
	"rise", "rises", "rose", "risen", "rising",
	"road", "roads",
	"roll", "rolls", "rolled", "rolling",
	"room", "rooms", "roomed", "rooming",
	"round", "rounder",
	"run", "runs", "ran", "run", "running", "runner", "runners",
	"safe", "safer", "safest", "safes",
	"same",
	"save", "saves", "saved", "saving",
	"say", "says", "said", "saying",
	"school", "schools", "schooled",
	"seat", "seats", "seated", "seating",
	"second", "seconds", "seconded", "seconding",
	"see", "sees", "saw", "seen", "seeing",
	"seem", "seems", "seemed", "seeming",
	"sell", "sells", "sold", "selling", "seller", "sellers",
	"send", "sends", "sent", "sending", "sender", "senders",
	"sense", "senses", "sensed", "sensing",
	"serious",
	"serve", "serves", "served", "serving",
	"service", "services", "serviced", "servicing",
	"set", "sets", "set", "setting",
	"settle", "settles", "settled", "settling",
	"seven", "sevens",
	"sex", "sexes",
	"share", "shares", "shared", "sharing",
	"she",
	"sheet", "sheets",
	"shoe", "shoes", "shod", "shoeing",
	"shoot", "shoots", "shot", "shooting", "shooter", "shooters",
	"shop", "shops", "shopped", "shopping",
	"short", "shorter", "shortest",
	"should",
	"show", "shows", "showed", "shown", "showing",
	"shut", "shuts", "shut", "shutting",
	"sick", "sicker", "sickest",
	"side", "sides", "sided", "siding",
	"sign", "signs", "signed", "signing",
	"singe",
	"simple", "simpler", "simplest", "simples",
	"since",
	"sing", "sings", "sang", "sung", "singing",
	"single", "singles", "singled", "singling",
	"sir", "sirs",
	"sister", "sisters",
	"sit", "sits", "sat", "sitting",
	"six", "sixes",
	"size", "sizes", "sized", "sizing",
	"sleep", "sleeps", "slept", "sleeping", "sleeper", "sleepers",
	"slow", "slower", "slowest", "slows", "slowed", "slowing",
	"small", "smaller", "smallest",
	"smoke", "smokes", "smoked", "smoking", "smoker", "smokers",
	"so",
	"some",
	"son", "sons",
	"soon",
	"sorry", "sorrier", "sorriest",
	"sort", "sorts", "sorted", "sorting",
	"sound", "sounds", "sounded", "sounding",
	"south",
	"space", "spaces", "spaced", "spacing",
	"speak", "speaks", "spoke", "spoken", "speaking", "speaker", "speakers",
	"special",
	"spend", "spends", "spent", "spending", "spender", "spenders",
	"stage", "stages",
	"stairs", "stairs",
	"stand", "stands", "stood", "standing",
	"start", "starts", "started", "starting", "starter", "starting",
	"state", "states", "stated", "stating",
	"station", "stations", "stationed", "stationing",
	"stay", "stays", "stayed", "staying",
	"step", "steps", "stepped", "stepping",
	"stick", "sticks", "stuck", "sticking", "sticker", "stickers",
	"still",
	"stop", "stops", "stopped", "stopping",
	"story", "stories",
	"straight", "straighter", "straightest", "straights",
	"street", "streets",
	"strike", "strikes", "struck", "striking",
	"strong", "stronger", "strongest",
	"student", "students",
	"study", "studies", "studied", "studying",
	"stuff", "stuffs", "stuffed", "stuffing",
	"stupid", "stupider", "stupidest",
	"such",
	"suddenly",
	"suggest", "suggests", "suggested", "suggesting",
	"suit", "suits", "suited", "suiting",
	"summer", "summers",
	"sun", "suns",
	"suppose", "supposes", "supposed", "supposing",
	"sure", "surer", "surest",
	"surprise", "surprises", "surprised", "surprising",
	"system", "systems",
	"table", "tables",
	"take", "takes", "took", "taken", "taking", "taker", "takers",
	"talk", "talks", "talked", "talking", "talker", "talkers",
	"tea", "teas",
	"teach", "teaches", "taught", "teaching", "teacher", "teachers",
	"team", "teams", "teamed", "teaming",
	"television", "televisions",
	"tell", "tells", "told", "telling",
	"ten", "tens",
	"terrible",
	"than",
	"thank", "thanks", "thanked", "thanking",
	"the",
	"then",
	"there",
	"they",
	"thing", "things",
	"think", "thinks", "thought", "thinking", "thinker", "thinkers",
	"thirty", "thirties",
	"this",
	"though",
	"three", "threes",
	"through",
	"throw", "throws", "threw", "thrown", "throwing", "thrower", "throwing",
	"tie", "ties", "tied", "tying",
	"time", "times", "timed", "timing", "timer", "timers",
	"to",
	"today",
	"together",
	"tomorrow",
	"tonight",
	"too",
	"top", "tops",
	"touch", "touches", "touched", "touching", "toucher", "touchers",
	"toward", "towards",
	"town", "towns",
	"train", "trains", "trained", "training",
	"travel", "travels", "traveled", "traveling", "travelled", "travelling", "traveler", "travelers",
	"tree", "trees", "treed", "treeing",
	"trouble", "troubles", "troubled", "troubling",
	"true", "truer", "truest",
	"trust", "trusts", "trusted", "trusting", "truster", "trusters",
	"try", "tries", "tried", "trying",
	"turn", "turns", "turned", "turning",
	"twenty", "twenties",
	"two", "twos",
	"under",
	"understand", "understands", "understood", "understanding",
	"unless",
	"until",
	"up", "ups", "upped", "upping",
	"upon",
	"use", "uses", "used", "using",
	"usual",
	"very",
	"view", "views", "viewed", "viewing",
	"village", "villages",
	"visit", "visits", "visited", "visiting", "visitor", "visitors",
	"wait", "waits", "waited", "waiting",
	"walk", "walks", "walked", "walking", "walker", "walkers",
	"wall", "walls",
	"want", "wants", "wanted", "wanting", "wanter", "wanters",
	"war", "wars", "warred", "warring",
	"warm", "warmer", "warmest", "warms", "warmed", "warming",
	"wash", "washes", "washed", "washing",
	"watch", "watches", "watched", "watching",
	"water", "waters", "watered", "watering",
	"way", "ways",
	"we",
	"wear", "wears", "wore", "worn", "wearing",
	"week", "weeks",
	"well", "better", "best", "wells",
	"west",
	"what",
	"when",
	"where",
	"whether",
	"which",
	"while",
	"white", "whites", "whiter", "whitest",
	"who",
	"whole", "wholes",
	"why",
	"wide", "wider", "widest",
	"wife", "wives",
	"will", "wills", "willed", "willing",
	"win", "wins", "won", "winning",
	"wind", "winds", "wound", "winding",
	"window", "windows",
	"wish", "wishes", "wished", "wishing",
	"with",
	"within",
	"without",
	"woman", "women",
	"wonder", "wonders", "wondered", "wondering",
	"wood", "woods",
	"word", "words", "worded", "wording",
	"work", "works", "worked", "working", "worker", "workers",
	"world", "worlds",
	"worry", "worries", "worried", "worrying",
	"worse", "worse", "worst",
	"would",
	"write", "writes", "wrote", "written", "writing", "writer",
	"wrong", "wrongs", "wronged", "wronging",
	"year", "years",
	"yes", "yeses",
	"yet",
	"you",
	"young", "younger", "youngest",
]
